### ISSUE TITLE
我來提供具體意見

### ISSUE THREAD

**Issue by aikahiiragi** [enderseven1/Mizuki-Ming#1]
目前的問題：

1. [README.md](https://github.com/enderseven1/Mizuki-Ming#readme)的標題仍然是“I.Ming-Mizuki”，這個係大忌，應該改成“Mizuki-Ming”。（極重要）
2. 欠缺LICENSE.md，必須加上，其內容也必須是IPA Font License Agreement v1.0，即是與[一點明體/IPA明朝的LICENSE.md一樣](https://github.com/ichitenfont/I.Ming/blob/master/LICENSE.md)。（極重要）
3. 不應該直接話“所以我只能将其进行修改，望一点字坊可以谅解”，應該話“所以我利用IPA明朝，將某些字形修改成接近大陸使用的新字形，並且利用或借用了一點明體的大量成果，來完成這個水木明体。”
4. 修改了什麼字或偏旁，應該寫出來讓人知道的，但會寫在HISTORY.md。

**Comment by enderseven1** [comment]
好的。
