### ISSUE TITLE
“户”部件

### ISSUE THREAD

**Issue by garfieldLSY** [enderseven1/Mizuki-Ming#5]
是不是可以把“户”做爲部件時的第一筆改爲長横？（我觉得對應楷體中的點，長横楷化了就是點）

**Comment by enderseven1** [comment]
行，我考虑考虑，最近要上课，不一定有时间（你不是北京人吗，为什么打繁体字）

**Comment by garfieldLSY** [comment]
矯正輸入法呢。（用的拼音，繁體輸入槽點比較多）

**Comment by enderseven1** [comment]
我刚才去查了一下，大陆字形的所字与其他带户的字形都不同，户字上方为丿是为了统一字形。不过我可以做一个变体版本，当然我未必有时间，等把通规表补完罢。

**Comment by garfieldLSY** [comment]
我已經在小破站上給你發消息了，有甚麽事在小破站上説。
